// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";

// Cargar .env y luego .env.local (override) para que Prisma use la misma URL que Next en local
dotenv.config();
dotenv.config({ path: ".env.local", override: true });

import { defineConfig } from "prisma/config";

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable "${name}" for Prisma configuration.`);
  }
  return value;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: requireEnv("DATABASE_URL"),
  },
});
